USE training;

DROP TABLE IF EXISTS steps;

CREATE TABLE steps (
    id INT AUTO_INCREMENT PRIMARY KEY,
    person_id INT NOT NULL,
    date DATE NOT NULL,
    steps INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
